import csv
from .base import BaseParser
from .registry import ParserRegistry

@ParserRegistry.register("wiz")
class CSVWizParser(BaseParser):
    """
    A parser class for processing CSV files generated by Wiz that contain AWS resources.

    This class extends the `BaseParser` class and is registered in the `ParserRegistry` under the name "wiz".
    It reads a CSV file, identifies AWS resource ARNs using a column ending with "providerUniqueId",
    and returns a list of these resource ARNs.

    Methods:
        parse(file_path: str) -> list:
            Parses a Wiz-generated CSV file and extracts AWS resource ARNs.

    Example:
        parser = ParserRegistry.get_parser("wiz")
        resources = parser.parse("wiz_aws_resources.csv")
    """

    @staticmethod
    def parse(file_path: str) -> list:
        """
        Parses a Wiz-generated CSV file to extract AWS resource ARNs.

        Args:
            file_path (str): The file path to the Wiz-generated CSV file.

        Returns:
            list: A list of AWS resource ARNs extracted from the file.

        Raises:
            KeyError: If no column ending with "providerUniqueId" is found in the CSV file.
        """
        resources = []
        with open(file_path, 'r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                # Identify required columns using suffix search
                resource_arn_column = next((col for col in row if col.endswith("providerUniqueId")), None)
                if not resource_arn_column:
                    raise KeyError("No column ending with 'providerUniqueId' found in the CSV file.")
                resource_arn = row[resource_arn_column]
                resources.append(resource_arn)
        return resources
